from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.colors import HexColor
import os

def generate_pdf(gene_name: str, report: str, drugs_info: str) -> str:
    
    # PDF file ka naam
    filename = f"reports/{gene_name}_medical_report.pdf"
    os.makedirs("reports", exist_ok=True)
    
    doc = SimpleDocTemplate(filename, pagesize=A4,
                           rightMargin=inch, leftMargin=inch,
                           topMargin=inch, bottomMargin=inch)
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle('Title',
                                fontSize=24,
                                textColor=HexColor('#1a472a'),
                                spaceAfter=20,
                                fontName='Helvetica-Bold',
                                alignment=1)
    
    heading_style = ParagraphStyle('Heading',
                                  fontSize=14,
                                  textColor=HexColor('#2d6a4f'),
                                  spaceBefore=15,
                                  spaceAfter=8,
                                  fontName='Helvetica-Bold')
    
    body_style = ParagraphStyle('Body',
                               fontSize=11,
                               textColor=HexColor('#333333'),
                               spaceAfter=8,
                               leading=16,
                               fontName='Helvetica')
    
    elements = []
    
    # Title
    elements.append(Paragraph("BioMed AI Report", title_style))
    elements.append(HRFlowable(width="100%", thickness=2, color=HexColor('#2d6a4f')))
    elements.append(Spacer(1, 20))
    
    # Gene Info
    elements.append(Paragraph(f"Gene Analysis: {gene_name}", heading_style))
    elements.append(HRFlowable(width="100%", thickness=1, color=HexColor('#cccccc')))
    elements.append(Spacer(1, 10))
    
    # Medical Report
    elements.append(Paragraph("Medical Report", heading_style))
    for line in report.split('\n'):
        if line.strip():
            clean_line = line.replace('**', '').strip()
            elements.append(Paragraph(clean_line, body_style))
    
    elements.append(Spacer(1, 20))
    elements.append(HRFlowable(width="100%", thickness=1, color=HexColor('#cccccc')))
    
    # Drug Information
    elements.append(Paragraph("Drug Information", heading_style))
    for line in drugs_info.split('\n'):
        if line.strip():
            clean_line = line.replace('**', '').strip()
            elements.append(Paragraph(clean_line, body_style))
    
    elements.append(Spacer(1, 20))
    elements.append(HRFlowable(width="100%", thickness=2, color=HexColor('#2d6a4f')))
    elements.append(Paragraph("Generated by BioMed AI — For educational purposes only.", 
                              ParagraphStyle('Footer', fontSize=9, 
                                           textColor=HexColor('#999999'),
                                           alignment=1)))
    
    doc.build(elements)
    print(f"PDF ban gaya: {filename}")
    return filename

if __name__ == "__main__":
    generate_pdf("BRCA1", "Test Report Content", "Test Drug Info")
